### ISSUE TITLE
Reporting Outdated routes

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#26] opened 2016-05-15 18:39 UTC
Is it possible to have airports ICAO codes in the ticket subject ? it will allow me and Chris automatically see if this is ticket for me or Chris. Because I guess we are unable to direct those tickets to right OM ? 

maybe instead of tickets we could add OM emails addresses to areas.  ?  if someone click "report outdated route"  it is sending email directly with possibility to replay to person .and maybe open form with route implement in form which user cannot change but it will have reason box which will have to fill in and it maybe will stop so many tickets to be coming in . ?

**Comment by LukasJK** [comment] 2016-05-15 22:30
As discussed previously - outdated route reports will go to VDS in the future

**Comment by soferek** [comment] 2016-05-15 22:40
I forgot :P

**Comment by LukasJK** [comment] 2016-05-15 23:34
Duplicate of LukasJK/vAMSYSissues#17

**Closed** 2016-05-15 23:34 UTC
Labels: enhancement, VDS
